language: objective-c
before_install:
    - (ruby --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - sudo motion update --cache-version=3.2
gemfile:
  - Gemfile
script:
    - bundle install
    - bundle exec rake clean
    - TRAVIS_CI=1 bundle exec rake spec
