site_name: ProMotion Documentation
theme: readthedocs
pages:
- ["index.md", "Welcome"]
- ["Guide - Getting Started.md", "Guide - Getting Started"]
- ["Guide - Making Your Own Screens.md", "Guide - Making Your Own Screens"]
- ["Tutorials, Screencasts, Articles, Presentations.md", "Tutorials, Screencasts, Articles, Presentations"]
- ["API Reference - Command Line Tool.md", "API Reference - Command Line Tool"]
- ["API Reference - ProMotion Delegate.md", "API Reference - ProMotion Delegate"]
- ["API Reference - ProMotion Logger.md", "API Reference - ProMotion Logger"]
- ["API Reference - ProMotion MapScreen.md", "API Reference - ProMotion MapScreen"]
- ["API Reference - ProMotion PushNotification.md", "API Reference - ProMotion PushNotification"]
- ["API Reference - ProMotion Screen.md", "API Reference - ProMotion Screen"]
- ["API Reference - ProMotion SplitScreen.md", "API Reference - ProMotion SplitScreen"]
- ["API Reference - ProMotion Styling.md", "API Reference - ProMotion Styling"]
- ["API Reference - ProMotion Table - Cell Options.md", "API Reference - ProMotion Table - Cell Options"]
- ["API Reference - ProMotion TableScreen.md", "API Reference - ProMotion TableScreen"]
- ["API Reference - ProMotion Tabs.md", "API Reference - ProMotion Tabs"]
- ["API Reference - ProMotion WebScreen.md", "API Reference - ProMotion WebScreen"]
- ["Add-On-Gems.md", "Add-On-Gems"]
- ["Migration Guide - ProMotion-1.2-to-2.0.md", "Migration Guide - ProMotion-1.2-to-2.0"]
- ["ProMotion Apps.md", "ProMotion Apps"]
