site_name: ProMotion Documentation
theme: readthedocs
pages:
- ["README.md", "Welcome"]
- ["Guides/Guide - Getting Started.md", "Guide - Getting Started"]
- ["Guides/Guide - Making Your Own Screens.md", "Guide - Making Your Own Screens"]
- ["Guides/Migration Guide - ProMotion-1.2-to-2.0.md", "Migration Guide - ProMotion-1.2-to-2.0"]
- ["Reference/API Reference - Command Line Tool.md", "API Reference - Command Line Tool"]
- ["Reference/API Reference - ProMotion Delegate.md", "API Reference - ProMotion Delegate"]
- ["Reference/API Reference - ProMotion Logger.md", "API Reference - ProMotion Logger"]
- ["Reference/API Reference - ProMotion MapScreen.md", "API Reference - ProMotion MapScreen"]
- ["Reference/API Reference - ProMotion PushNotification.md", "API Reference - ProMotion PushNotification"]
- ["Reference/API Reference - ProMotion Screen.md", "API Reference - ProMotion Screen"]
- ["Reference/API Reference - ProMotion SplitScreen.md", "API Reference - ProMotion SplitScreen"]
- ["Reference/API Reference - ProMotion Styling.md", "API Reference - ProMotion Styling"]
- ["Reference/API Reference - ProMotion Table - Cell Options.md", "API Reference - ProMotion Table - Cell Options"]
- ["Reference/API Reference - ProMotion TableScreen.md", "API Reference - ProMotion TableScreen"]
- ["Reference/API Reference - ProMotion Tabs.md", "API Reference - ProMotion Tabs"]
- ["Reference/API Reference - ProMotion WebScreen.md", "API Reference - ProMotion WebScreen"]
- ["Tutorials, Screencasts, Articles, Presentations.md", "Tutorials, Screencasts, Articles, Presentations"]
- ["Add-On-Gems.md", "Add-On-Gems"]
- ["ProMotion Apps.md", "ProMotion Apps"]
